# Polish translations for woeusb package
# Polskie tłumaczenia dla pakietu woeusb.
# Copyright (C) 2018 THE woeusb'S COPYRIGHT HOLDER
# This file is distributed under the same license as the woeusb package.
# Jakub Szymański <jakubmateusz@poczta.onet.pl>, 2018.
#
msgid ""
msgstr ""
"Project-Id-Version: woeusb\n"
"Report-Msgid-Bugs-To: WoeUSB Issue Tracker <https://github.com/slacka/WoeUSB/"
"issues>\n"
"POT-Creation-Date: 2020-12-28 10:21+0100\n"
"PO-Revision-Date: 2020-12-28 15:46+0100\n"
"Last-Translator: Jakub Szymański <jakubmateusz@poczta.onet.pl>\n"
"Language-Team: Polish\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Poedit-Basepath: ../../..\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2);\n"
"X-Generator: Poedit 2.4.1\n"
"X-Poedit-SearchPath-0: .\n"

#: core.py:85
msgid "You need to specify installation type (--device or --partition)"
msgstr "Musisz zdefiniować typ instalacji (--device or --partition)"

#: core.py:148
#, python-brace-format
msgid "Warning: You are not running {0} as root!"
msgstr "Uwaga: {0} nie jest uruchomiony jako root!"

#: core.py:149
msgid "Warning: This might be the reason of the following failure."
msgstr "Uwaga: To może być przyczyną niepowodzenia."

#: core.py:163
msgid "Error: Unable to mount source filesystem"
msgstr "Błąd: Nie można było zmontować źródłowego systemu plików"

#: core.py:186
msgid "Error: Unable to mount target filesystem"
msgstr "Błąd: Nie można było zmontować docelowego systemu plików"

#: core.py:222
#, python-brace-format
msgid "Wiping all existing partition table and filesystem signatures in {0}"
msgstr "Usuwanie tablicy partycji i sygnatur systemów plików z {0}"

#: core.py:236
#, python-brace-format
msgid "Ensure that {0} is really wiped..."
msgstr "Upewniam się że {0} jest wyczyszczony..."

#: core.py:243
msgid ""
"Error: Partition is still detected after wiping all signatures, this "
"indicates that the drive might be locked into readonly mode due to end of "
"lifespan."
msgstr ""
"Błąd: Partycja jest nadal widoczna po jej usunięciu, to może wskazywać na "
"dysk tylko do odczytu, prawdopodobnie z powodu jego wysokiego zużycia."

#: core.py:257
#, python-brace-format
msgid "Creating new partition table on {0}..."
msgstr "Tworzenie nowej tablicy partycji na {0}..."

#: core.py:262
msgid "Error: Currently GUID partition table is not supported."
msgstr "Błąd: Obecnie tablica partycji GUID nie jest wspierana."

#: core.py:265
msgid "Error: Partition table not supported."
msgstr "Błąd: Tablica partycji nie jest wspierana."

#: core.py:292
msgid "Error: Filesystem not supported"
msgstr "Błąd: System plików nie jest wspierany"

#: core.py:295
msgid "Creating target partition..."
msgstr "Tworzenie docelowej partycji..."

#: core.py:326
#, python-brace-format
msgid "FATAL: Illegal {0}, please report bug."
msgstr "BŁĄD: Niedozwolony typ partycji {0}, proszę zgłoś ten błąd."

#: core.py:338
msgid "FATAL: Shouldn't be here"
msgstr "BŁĄD: Nie powinieneś tego widzieć, proszę zgłoś błąd"

#: core.py:378
msgid ""
"Warning: Unable to download UEFI:NTFS partition image from GitHub, "
"installation skipped.  Target device might not be bootable if the UEFI "
"firmware doesn't support NTFS filesystem."
msgstr ""
"Uwaga: Nie można było pobrać partycji UEFI:NTFS z GitHub'a, pomijam jej "
"instalacje.  Urządzenie docelowe może nie być bootowalne jeśli UEFI nie "
"wspiera NTFS."

#: core.py:394
msgid "Mounting source filesystem..."
msgstr "Montowanie systemu źródłowego..."

#: core.py:399 core.py:434
#, python-brace-format
msgid "Error: Unable to create {0} mountpoint directory"
msgstr "Błąd: Nie można było stworzyć folderu dla punktu montowania {0}"

#: core.py:408 core.py:415
msgid "Error: Unable to mount source media"
msgstr "Błąd: Nie można było zmontować źródła"

#: core.py:429
msgid "Mounting target filesystem..."
msgstr "Montowanie systemu docelowego..."

#: core.py:440
msgid "Error: Unable to mount target media"
msgstr "Błąd: Nie można było zmontować celu"

#: core.py:462
msgid "Copying files from source media..."
msgstr "Kopiowanie plików z źródła..."

#: core.py:520
msgid "Installing GRUB bootloader for legacy PC booting support..."
msgstr "Instalacja GRUB dla możliwości bootowania na starszych komputerach..."

#: core.py:541
msgid "Installing custom GRUB config for legacy PC booting..."
msgstr "Instalacja własnej konfiguracji GRUB..."

#: core.py:560
#, python-brace-format
msgid "Unmounting and removing {0}..."
msgstr "Odmontowywanie i usuwanie {0}..."

#: core.py:562
msgid "Warning: Unable to unmount filesystem."
msgstr "Uwaga: Nie można było odmontować systemu plików."

#: core.py:568
msgid "Warning: Unable to remove source mountpoint"
msgstr "Uwaga: Nie można było usunąć punktu montowania źródła"

#: core.py:600 core.py:607
msgid ""
"Some mountpoints are not unmount/cleaned successfully and must be done "
"manually"
msgstr ""
"Niektóre punkty montowania nie są odmontowane/wyczyszczone poprawnie i "
"wymagają manualnej interwencji"

#: core.py:605
msgid ""
"We unable to unmount target filesystem for you, please make sure target "
"filesystem is unmounted before detaching to prevent data corruption"
msgstr ""
"Nie udało się odmontować docelowego dysku, aby uniknąć utraty danych proszę "
"upewnij się że jest on odmontowany"

#: core.py:612
msgid ""
"Target device is busy, please make sure you unmount all filesystems on "
"target device or shutdown the computer before detaching it."
msgstr ""
"Docelowe urządzenie jest zajęte, proszę upewnij się że jest ono odmontowane "
"albo wyłącz komputer przed odłączeniem go."

#: core.py:615
msgid "You may now safely detach the target device"
msgstr "Teraz możesz bezpiecznie odłączyć dysk docelowy"

#: core.py:620
msgid "Done :)"
msgstr "Gotowe :)"

#: core.py:621
msgid "The target device should be bootable now"
msgstr "Dysk docelowy powinien być bootowalny"

#: gui.py:34
msgid "Show all drives"
msgstr "Pokaż wszystkie dyski"

#: gui.py:35
msgid "Show all drives, even those not detected as USB stick."
msgstr ""
"Pokaż wszystkie dyski, nawet jeśli system nie widzi ich jako pamięci USB."

#: gui.py:46
msgid "Set boot flag"
msgstr "Ustaw flagę \"boot\""

#: gui.py:47
msgid "Sets boot flag after process of copying."
msgstr "Ustawia flagę \"boot\" po zakończeniu kopiowania."

#: gui.py:49
msgid "Use NTFS"
msgstr "Użyj NTFS"

#: gui.py:50
msgid "Use NTFS instead of FAT. NOTE: NTFS seems to be slower than FAT."
msgstr "Użyj NTFS zamiast FAT. Notka: NTFS zdaje się być wolniejszy od FAT."

#: gui.py:56
msgid "&File"
msgstr "&Plik"

#: gui.py:57
msgid "&Options"
msgstr "&Opcje"

#: gui.py:58
msgid "&Help"
msgstr "&Pomoc"

#: gui.py:114
msgid "Source :"
msgstr "Źródło :"

#: gui.py:117
msgid "From a disk image (iso)"
msgstr "Z pliku (iso)"

#: gui.py:122
msgid "Please select a disk image"
msgstr "Prosze wybierz obraz dysku"

#: gui.py:128
msgid "From a CD/DVD drive"
msgstr "Z napędu optycznego"

#: gui.py:141
msgid "Target device :"
msgstr "Urządzenie docelowe :"

#: gui.py:153
msgid "Install"
msgstr "Instaluj"

#: gui.py:243
msgid "Installing"
msgstr "Instalacja"

#: gui.py:243
msgid "Please wait..."
msgstr "Proszę czekać..."

#: gui.py:254
msgid "Are you sure you want to cancel the installation?"
msgstr "Jesteś pewnien że chcesz przerwać instalacje?"

#: gui.py:254
msgid "Cancel"
msgstr "Przerwij"

#: gui.py:263
msgid "Installation succeeded!"
msgstr "Instalacja zakończyła się sukcesem!"

#: gui.py:263 gui.py:265
msgid "Installation"
msgstr "Instalacja"

#: gui.py:265
msgid "Installation failed!"
msgstr "Instalacja zakończyła się niepowodzeniem!"

#: gui.py:281
msgid "About"
msgstr "O programie"

#: gui.py:312
msgid "Authors"
msgstr "Autorzy"

#: gui.py:315
msgid "Original WinUSB Developer"
msgstr "Deweloper oryginalnego WoeUSB"

#: gui.py:317
msgid ""
"\n"
"            This file is part of WoeUSB-ng.\n"
"\n"
"            WoeUSB-ng is free software: you can redistribute it and/or "
"modify\n"
"            it under the terms of the GNU General Public License as "
"published by\n"
"            the Free Software Foundation, either version 3 of the License, "
"or\n"
"            (at your option) any later version.\n"
"\n"
"            WoeUSB-ng is distributed in the hope that it will be useful,\n"
"            but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
"            MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
"            GNU General Public License for more details.\n"
"\n"
"            You should have received a copy of the GNU General Public "
"License\n"
"            along with WoeUSB-ng.  If not, see <http://www.gnu.org/licenses/"
">.\n"
"        "
msgstr ""
"\n"
"            Ten plik jest częścią WoeUSB-ng.\n"
"\n"
"             WoeUSB-ng jest wolnym oprogramowaniem: możesz go rozprowadzać "
"dalej\n"
"            i/lub modyfikować na warunkach Powszechnej Licencji Publicznej "
"GNU (GNU GPL),\n"
"            wydanej przez Fundację Wolnego Oprogramowania - według wersji 3 "
"tej\n"
"            Licencji lub (według twojego wyboru) którejś z późniejszych "
"wersji.\n"
"\n"
"             WoeUSB-ng rozpowszechniany jest z nadzieją, iż będzie on\n"
"            użyteczny - jednak BEZ JAKIEJKOLWIEK GWARANCJI, nawet domyślnej\n"
"            gwarancji PRZYDATNOŚCI HANDLOWEJ albo PRZYDATNOŚCI DO "
"OKREŚLONYCH\n"
"            ZASTOSOWAŃ. W celu uzyskania bliższych informacji sięgnij do\n"
"            Powszechnej Licencji Publicznej GNU.\n"
"\n"
"            Z pewnością wraz z WoeUSB-ng otrzymałeś też egzemplarz\n"
"            Powszechnej Licencji Publicznej GNU (GNU General Public "
"License).\n"
"            Jeśli nie - zobacz <http://www.gnu.org/licenses/>.\n"
" "

#: gui.py:337
msgid "License"
msgstr "Licencja"

#: utils.py:38
#, python-brace-format
msgid ""
"Error: {0} requires {1} command in the executable search path, but it is not "
"found."
msgstr ""
"Błąd: {0} wymaga komendy {1} w ścieżkach do plików wykonywalnych, ale nie "
"została ona znaleziona."

#: utils.py:50
msgid "Error: mkdosfs/mkfs.msdos/mkfs.vfat/mkfs.fat command not found!"
msgstr "Błąd: Nie znaleziono mkdosfs/mkfs.msdos/mkfs.vfat/mkfs.fat!"

#: utils.py:51
msgid "Error: Please make sure that dosfstools is properly installed!"
msgstr "Błąd: Proszę upewnij się że dosfstools jest poprawnie zainstalowane!"

#: utils.py:56
msgid "Error: mkntfs command not found!"
msgstr "Błąd: Nie znaleziono mkntfs!"

#: utils.py:57
msgid "Error: Please make sure that ntfs-3g is properly installed!"
msgstr "Błąd: Proszę upewnij się że ntfs-3g jest poprawnie zainstalowane!"

#: utils.py:67
msgid "Error: grub-install or grub2-install command not found!"
msgstr "Błąd: Nie znaleziono grub-install ani grub2-install!"

#: utils.py:68
msgid "Error: Please make sure that GNU GRUB is properly installed!"
msgstr "Błąd: Proszę upewnij się że GNU GRUB jest poprawnie zainstalowane!"

#: utils.py:86
#, python-brace-format
msgid ""
"Error: Source media \"{0}\" not found or not a regular file or a block "
"device file!"
msgstr ""
"Błąd: Medium źródłowe \"{0}\" nie zostało znalezione lub nie jest ono "
"zwykłym plikiem lub urządzeniem blokowym!"

#: utils.py:92
#, python-brace-format
msgid "Error: Target media \"{0}\" is not a block device file!"
msgstr "Błąd: Medium docelowe \"{0}\" nie jest urządzeniem blokowym!"

#: utils.py:96
#, python-brace-format
msgid "Error: Target media \"{0}\" is not an entire storage device!"
msgstr "Błąd: Medium docelowe \"{0}\" nie jest całym urządzeniem!"

#: utils.py:100
#, python-brace-format
msgid "Error: Target media \"{0}\" is not an partition!"
msgstr "Błąd: Medium docelowe \"{0}\" nie jest partycją!"

#: utils.py:122
#, python-brace-format
msgid "Info: Target device is {0}"
msgstr "Info: Urządzenie docelowe to {0}"

#: utils.py:123
#, python-brace-format
msgid "Info: Target partition is {0}"
msgstr "Info: Partycja docelowa to {0}"

#: utils.py:148
msgid ""
"Error: Source media is currently mounted, unmount the partition then try "
"again"
msgstr ""
"Błąd: Medium źródłowe jest obecnie zmontowane, odmontuj partycje i spróbuj "
"ponownie"

#: utils.py:153
msgid ""
"Error: Target partition is currently mounted, unmount the partition then try "
"again"
msgstr ""
"Błąd: Partycja docelowa jest obecnie zmontowana, odmontuj partycje i spróbuj "
"ponownie"

#: utils.py:160
msgid ""
"Error: Target device is currently busy, unmount all mounted partitions in "
"target device then try again"
msgstr ""
"Błąd: Urządzenie docelowe jest zajęte, odmontuj wszystkie zmontowane "
"partycje na urządzeniu docelowym i spróbuj ponownie"

#: utils.py:176
#, python-brace-format
msgid ""
"Warining: File {0} in source image has exceed the FAT32 Filesystem 4GiB "
"Single File Size Limitation, swiching to NTFS filesystem."
msgstr ""
"Uwaga: Plik {0} w obrazie źródłowym przekroczył limit 4GiB dla jednego pliku "
"w systemie plików FAT32, przełączanie się na NTFS."

#: utils.py:181
msgid ""
"Refer: https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-"
"filesystem-4gib-single-file-size-limitation for more info."
msgstr ""
"Odwiedź: https://github.com/slacka/WoeUSB/wiki/Limitations#fat32-"
"filesystem-4gib-single-file-size-limitation aby dowiedzieć się więcej."

#: utils.py:205
msgid ""
"Error: Target filesystem not supported, currently supported filesystem: FAT, "
"NTFS."
msgstr ""
"Błąd: Docelowy system plików nie jest wspierany, obecnie wspierane są FAT i "
"NTFS."

#: utils.py:226
msgid ""
"Warning: Your device doesn't seems to have an UEFI:NTFS partition, UEFI "
"booting will fail if the motherboard firmware itself doesn't support NTFS "
"filesystem!"
msgstr ""
"Uwaga: Twoje urządzenie zdaje się nie mieć partycji UEFI:NTFS, bootowanie "
"UEFI nie powiedzie się jeśli firmware nie wspiera systemu NTFS!"

#: utils.py:229
msgid ""
"Info: You may recreate disk with an UEFI:NTFS partition by using the --"
"device creation method"
msgstr ""
"Info: Możesz stworzyć dysk z partycją UEFI:NTFS używając opcji --device"

#: utils.py:261
msgid "Error: Not enough free space on target partition!"
msgstr "Bład: Brak wystarczającej ilości miejsca na partycji docelowej!"

#: utils.py:263
#, python-brace-format
msgid "Error: We required {0}({1} bytes) but '{2}' only has {3}({4} bytes)."
msgstr "Błąd: Potrzebujemy {0}({1} bajtów) ale '{2}' ma tylko {3}({4} bajtów}."

#: workaround.py:16
msgid "Making system realize that partition table has changed..."
msgstr "Powiadamianie systemu że tablica partycji się zmieniła..."

#: workaround.py:19
msgid "Wait 3 seconds for block device nodes to populate..."
msgstr "Czekanie 3 sekundy na aktualizacje urządzeń blokowych..."

#: workaround.py:35
msgid ""
"Applying workaround for buggy motherboards that will ignore disks with no "
"partitions with the boot flag toggled"
msgstr ""
"Używanie obejścia dla zabugwanych płyt głównych które ignorują dyski które "
"nie mają partycji z ustawioną flagą \"boot\""

#: workaround.py:62
msgid ""
"Source media seems to be Windows 7-based with EFI support, applying "
"workaround to make it support UEFI booting"
msgstr ""
"Medium źródłowe zdaje się być Windows 7 ze wsparciem EFI, używanie obejścia "
"aby wspierał bootowanie UEFI"

#: workaround.py:71
#, python-brace-format
msgid "DEBUG: Can't find efi directory, use {0}"
msgstr ""

#: workaround.py:75 workaround.py:87
#, python-brace-format
msgid "DEBUG: {0} detected."
msgstr ""

#: workaround.py:83
#, python-brace-format
msgid "DEBUG: Can't find efi/boot directory, use {0}"
msgstr ""

#: workaround.py:95
msgid "INFO: Detected existing EFI bootloader, workaround skipped."
msgstr "Info: Wykryto istniejący bootloader EFI, obejście pominięte."
